Repository GroupBy-Side-Project-GSP/Test-Repo, pull requests merged in 2022-02, with the labels that each got.

#2 🔀 :: (#1) set toast
  app/src/main/java/com/gsp/test/MainActivity.kt
Labels: good first issue

#4 🔀 :: (#3) toast
  .idea/gradle.xml
  app/src/main/java/com/gsp/test/MainActivity.kt
Labels: enhancement

#7 🔀 :: (#6) sample
  app/src/main/java/com/gsp/test/MainActivity.kt
Labels: bug
